USE master;

GO

-- 创建主密钥
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '12345678';

-- 创建证书，证书名称为 CERT_XXX，每个节点证书名不可相同
CREATE CERTIFICATE CERT_XXX WITH SUBJECT = 'CERT_XXX', START_DATE = '2021-01-01', EXPIRY_DATE = '2099-12-30';

-- 将证书备份到文件
BACKUP CERTIFICATE CERT_XXX TO FILE = 'C:\CERT\CERT_XXX.CER';

-- 根据证书创建端点 ag1_endpoint ，所有端点名称最好保持一致
CREATE ENDPOINT [ag1_endpoint] AUTHORIZATION [sa] STATE=STARTED AS TCP (LISTENER_PORT = 5022, LISTENER_IP = ALL)
FOR DATA_MIRRORING (ROLE = ALL,AUTHENTICATION = CERTIFICATE CERT_XXX, ENCRYPTION = REQUIRED ALGORITHM AES)

GO